CMD_ECHO= echo
CMD_SED= sed

CXXFLAGS+= -g -I ..

TESTS+= ActorsClass_0
TESTS+= ActorsClass_1
TESTS+= ActorsClass_2
TESTS+= ActorsClass_3
TESTS+= ActorsClass_4
TESTS+= ActorsClass_6
TESTS+= ActorsClass_7
TESTS+= ActorsClass_8
TESTS+= ActorsClass_9
TESTS+= GetActorName
TESTS+= IsActorOrActress
TESTS+= IsMovie
TESTS+= GetName
TESTS+= GetTitle
TESTS+= TitlesClass_0
TESTS+= TitlesClass_1
TESTS+= TitlesClass_2
TESTS+= TitlesClass_3

all: ${TESTS:=.out}
	@echo '========================================================'
	@if test -n "$$(find . -name "*.failed")"; \
	then echo 'Some tests failed: please check .failed files.'; \
	else echo 'All tests successful.'; \
	fi
	@echo '========================================================'

ActorsClass_0.test: t_ActorsClass_0.cpp \
										../ActorsClass.h \
										../Prototypes.h \
										../Constants.h \
										../TitlesClass.h \
										../ActorsClass_Add.cpp \
										../ActorsClass_Constructor.cpp \
										../ActorsClass_Destructor.cpp \
										../ActorsClass_Distance.cpp \
										../ActorsClass_Link.cpp \
										../ActorsClass_Selector.cpp \
										../ActorsClass_Size.cpp \
										../ActorsClass_Test.cpp \
										../GetMaxName.cpp \
										../IsActorOrActress.cpp \
										../IsMovie.cpp \
										../GetName.cpp \
										../GetTitle.cpp \
										../TitlesClass_Constructor.cpp \
										../TitlesClass_Destructor.cpp \
										../TitlesClass_Selector.cpp
	${CXX} ${CXXFLAGS} `${CMD_ECHO} $^ | ${CMD_SED} "s/[^ ]*\.h//g"`  -o $@

ActorsClass_1.test: t_ActorsClass_1.cpp \
										../ActorsClass.h \
										../Prototypes.h \
										../Constants.h \
										../TitlesClass.h \
										../ActorsClass_Add.cpp \
										../ActorsClass_Constructor.cpp \
										../ActorsClass_Destructor.cpp \
										../ActorsClass_Distance.cpp \
										../ActorsClass_Link.cpp \
										../ActorsClass_Selector.cpp \
										../ActorsClass_Size.cpp \
										../ActorsClass_Test.cpp \
										../GetMaxName.cpp \
										../IsActorOrActress.cpp \
										../GetName.cpp \
										../IsMovie.cpp \
										../GetTitle.cpp \
										../TitlesClass_Constructor.cpp \
										../TitlesClass_Destructor.cpp \
										../TitlesClass_Selector.cpp
	${CXX} ${CXXFLAGS} `${CMD_ECHO} $^ | ${CMD_SED} "s/[^ ]*\.h//g"`  -o $@

ActorsClass_2.test: t_ActorsClass_2.cpp \
										../ActorsClass.h \
										../Prototypes.h \
										../Constants.h \
										../TitlesClass.h \
										../ActorsClass_Add.cpp \
										../ActorsClass_Constructor.cpp \
										../ActorsClass_Destructor.cpp \
										../ActorsClass_Distance.cpp \
										../ActorsClass_Link.cpp \
										../ActorsClass_Selector.cpp \
										../ActorsClass_Size.cpp \
										../ActorsClass_Test.cpp \
										../GetMaxName.cpp \
										../IsActorOrActress.cpp \
										../IsMovie.cpp \
										../GetName.cpp \
										../GetTitle.cpp \
										../TitlesClass_Constructor.cpp \
										../TitlesClass_Destructor.cpp \
										../TitlesClass_Selector.cpp
	${CXX} ${CXXFLAGS} `${CMD_ECHO} $^ | ${CMD_SED} "s/[^ ]*\.h//g"`  -o $@

ActorsClass_3.test: t_ActorsClass_3.cpp \
										../ActorsClass.h \
										../Prototypes.h \
										../Constants.h \
										../TitlesClass.h \
										../ActorsClass_Add.cpp \
										../ActorsClass_Constructor.cpp \
										../ActorsClass_Destructor.cpp \
										../ActorsClass_Distance.cpp \
										../ActorsClass_Link.cpp \
										../ActorsClass_Selector.cpp \
										../ActorsClass_Size.cpp \
										../ActorsClass_Test.cpp \
										../GetMaxName.cpp \
										../IsActorOrActress.cpp \
										../IsMovie.cpp \
										../GetName.cpp \
										../GetTitle.cpp \
										../TitlesClass_Constructor.cpp \
										../TitlesClass_Destructor.cpp \
										../TitlesClass_Selector.cpp
	${CXX} ${CXXFLAGS} `${CMD_ECHO} $^ | ${CMD_SED} "s/[^ ]*\.h//g"`  -o $@

ActorsClass_4.test: t_ActorsClass_4.cpp \
										../ActorsClass.h \
										../Prototypes.h \
										../Constants.h \
										../TitlesClass.h \
										../ActorsClass_Add.cpp \
										../ActorsClass_Constructor.cpp \
										../ActorsClass_Destructor.cpp \
										../ActorsClass_Distance.cpp \
										../ActorsClass_Link.cpp \
										../ActorsClass_Selector.cpp \
										../ActorsClass_Size.cpp \
										../ActorsClass_Test.cpp \
										../GetMaxName.cpp \
										../IsActorOrActress.cpp \
										../IsMovie.cpp \
										../GetName.cpp \
										../GetTitle.cpp \
										../TitlesClass_Constructor.cpp \
										../TitlesClass_Destructor.cpp \
										../TitlesClass_Selector.cpp
	${CXX} ${CXXFLAGS} `${CMD_ECHO} $^ | ${CMD_SED} "s/[^ ]*\.h//g"`  -o $@

ActorsClass_6.test: t_ActorsClass_6.cpp \
										../ActorsClass.h \
										../Prototypes.h \
										../Constants.h \
										../TitlesClass.h \
										../ActorsClass_Add.cpp \
										../ActorsClass_Closeness.cpp \
										../ActorsClass_Constructor.cpp \
										../ActorsClass_Destructor.cpp \
										../ActorsClass_Distance.cpp \
										../ActorsClass_Link.cpp \
										../ActorsClass_Selector.cpp \
										../ActorsClass_Size.cpp \
										../ActorsClass_Test.cpp \
										../GetMaxName.cpp \
										../IsActorOrActress.cpp \
										../IsMovie.cpp \
										../GetName.cpp \
										../GetTitle.cpp \
										../TitlesClass_Constructor.cpp \
										../TitlesClass_Destructor.cpp \
										../TitlesClass_Selector.cpp
	${CXX} ${CXXFLAGS} `${CMD_ECHO} $^ | ${CMD_SED} "s/[^ ]*\.h//g"`  -o $@

ActorsClass_7.test: t_ActorsClass_7.cpp \
										../ActorsClass.h \
										../Prototypes.h \
										../Constants.h \
										../TitlesClass.h \
										../ActorsClass_Add.cpp \
										../ActorsClass_Lin.cpp \
										../ActorsClass_Constructor.cpp \
										../ActorsClass_Destructor.cpp \
										../ActorsClass_Distance.cpp \
										../ActorsClass_Link.cpp \
										../ActorsClass_Selector.cpp \
										../ActorsClass_Size.cpp \
										../ActorsClass_Test.cpp \
										../GetMaxName.cpp \
										../IsActorOrActress.cpp \
										../IsMovie.cpp \
										../GetName.cpp \
										../GetTitle.cpp \
										../TitlesClass_Constructor.cpp \
										../TitlesClass_Destructor.cpp \
										../TitlesClass_Selector.cpp
	${CXX} ${CXXFLAGS} `${CMD_ECHO} $^ | ${CMD_SED} "s/[^ ]*\.h//g"`  -o $@

ActorsClass_8.test: t_ActorsClass_8.cpp \
										../ActorsClass.h \
										../Prototypes.h \
										../Constants.h \
										../TitlesClass.h \
										../ActorsClass_Add.cpp \
										../ActorsClass_Harmonic.cpp \
										../ActorsClass_Constructor.cpp \
										../ActorsClass_Destructor.cpp \
										../ActorsClass_Distance.cpp \
										../ActorsClass_Link.cpp \
										../ActorsClass_Selector.cpp \
										../ActorsClass_Size.cpp \
										../ActorsClass_Test.cpp \
										../GetMaxName.cpp \
										../IsActorOrActress.cpp \
										../IsMovie.cpp \
										../GetName.cpp \
										../GetTitle.cpp \
										../TitlesClass_Constructor.cpp \
										../TitlesClass_Destructor.cpp \
										../TitlesClass_Selector.cpp
	${CXX} ${CXXFLAGS} `${CMD_ECHO} $^ | ${CMD_SED} "s/[^ ]*\.h//g"`  -o $@

ActorsClass_9.test: t_ActorsClass_9.cpp \
										../ActorsClass.h \
										../Prototypes.h \
										../Constants.h \
										../TitlesClass.h \
										../ActorsClass_Add.cpp \
										../ActorsClass_Degree.cpp \
										../ActorsClass_Constructor.cpp \
										../ActorsClass_Destructor.cpp \
										../ActorsClass_Distance.cpp \
										../ActorsClass_Link.cpp \
										../ActorsClass_Selector.cpp \
										../ActorsClass_Size.cpp \
										../ActorsClass_Test.cpp \
										../GetMaxName.cpp \
										../IsActorOrActress.cpp \
										../IsMovie.cpp \
										../GetName.cpp \
										../GetTitle.cpp \
										../TitlesClass_Constructor.cpp \
										../TitlesClass_Destructor.cpp \
										../TitlesClass_Selector.cpp
	${CXX} ${CXXFLAGS} `${CMD_ECHO} $^ | ${CMD_SED} "s/[^ ]*\.h//g"`  -o $@

GetActorName.test: t_GetActorName.cpp \
										../Prototypes.h \
										../Constants.h \
										../GetActorName.cpp \
										../GetName.cpp
	${CXX} ${CXXFLAGS} `${CMD_ECHO} $^ | ${CMD_SED} "s/[^ ]*\.h//g"`  -o $@

IsActorOrActress.test: t_IsActorOrActress.cpp \
										../Prototypes.h \
										../Constants.h \
										../IsActorOrActress.cpp
	${CXX} ${CXXFLAGS} `${CMD_ECHO} $^ | ${CMD_SED} "s/[^ ]*\.h//g"`  -o $@

GetName.test: t_GetName.cpp \
										../Prototypes.h \
										../Constants.h \
										../GetName.cpp
	${CXX} ${CXXFLAGS} `${CMD_ECHO} $^ | ${CMD_SED} "s/[^ ]*\.h//g"`  -o $@

IsMovie.test: t_IsMovie.cpp \
										../Prototypes.h \
										../Constants.h \
										../IsMovie.cpp
	${CXX} ${CXXFLAGS} `${CMD_ECHO} $^ | ${CMD_SED} "s/[^ ]*\.h//g"`  -o $@

GetTitle.test: t_GetTitle.cpp \
										../Prototypes.h \
										../Constants.h \
										../GetTitle.cpp
	${CXX} ${CXXFLAGS} `${CMD_ECHO} $^ | ${CMD_SED} "s/[^ ]*\.h//g"`  -o $@

TitlesClass_0.test: t_TitlesClass_0.cpp \
										../Prototypes.h \
										../Constants.h \
										../TitlesClass.h \
										../IsActorOrActress.cpp \
										../IsMovie.cpp \
										../GetName.cpp \
										../GetTitle.cpp \
										../TitlesClass_Constructor.cpp \
										../TitlesClass_Destructor.cpp \
										../TitlesClass_Selector.cpp
	${CXX} ${CXXFLAGS} `${CMD_ECHO} $^ | ${CMD_SED} "s/[^ ]*\.h//g"`  -o $@

TitlesClass_1.test: t_TitlesClass_1.cpp \
										../Prototypes.h \
										../Constants.h \
										../TitlesClass.h \
										../IsActorOrActress.cpp \
										../IsMovie.cpp \
										../GetName.cpp \
										../GetTitle.cpp \
										../TitlesClass_Constructor.cpp \
										../TitlesClass_Destructor.cpp \
										../TitlesClass_Selector.cpp
	${CXX} ${CXXFLAGS} `${CMD_ECHO} $^ | ${CMD_SED} "s/[^ ]*\.h//g"`  -o $@

TitlesClass_2.test: t_TitlesClass_2.cpp \
										../Prototypes.h \
										../Constants.h \
										../TitlesClass.h \
										../IsActorOrActress.cpp \
										../IsMovie.cpp \
										../GetName.cpp \
										../GetTitle.cpp \
										../TitlesClass_Constructor.cpp \
										../TitlesClass_Destructor.cpp \
										../TitlesClass_Selector.cpp
	${CXX} ${CXXFLAGS} `${CMD_ECHO} $^ | ${CMD_SED} "s/[^ ]*\.h//g"`  -o $@

TitlesClass_3.test: t_TitlesClass_3.cpp \
										../Prototypes.h \
										../Constants.h \
										../TitlesClass.h \
										../IsActorOrActress.cpp \
										../IsMovie.cpp \
										../GetName.cpp \
										../GetTitle.cpp \
										../TitlesClass_Constructor.cpp \
										../TitlesClass_Destructor.cpp \
										../TitlesClass_Selector.cpp
	${CXX} ${CXXFLAGS} `${CMD_ECHO} $^ | ${CMD_SED} "s/[^ ]*\.h//g"`  -o $@

clean:
	rm -f *.test *.out *.failed

.SUFFIXES: .out .test

.test.out:
	@echo -n "Testing ${^:.test=}... "; \
	./$< > $@; \
	if test -z "$$(diff $@ ${@:out=in})"; \
	then echo 'passed.'; \
	else echo 'failed.'; \
	diff $@ ${@:out=in} > ${@:out=failed}|| true; \
	fi
